
services:

  db:
    env_file: ".env"
    container_name: ${PROJECT_NAME}-db
    image: mariadb:12.0.2
    restart: always
    environment:
     MARIADB_DATABASE: ${MARIADB_DATABASE}
     MARIADB_USER: ${MARIADB_USER}
     MARIADB_PASSWORD: ${MARIADB_PASSWORD}
     MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ${PWD}/db:/var/lib/mysql
    networks:
      - wpnet


  wordpress:
    env_file: ".env"
    container_name: ${PROJECT_NAME}-wordpress
    image: wordpress:6.8.2-php8.3-apache
    restart: always
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST} 
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ${PWD}/wordpress:/var/www/html
    networks:
      - wpnet
    depends_on:
      - db

  phpmyadmin:
    env_file: ".env"
    container_name: ${PROJECT_NAME}-phpmyadmin
    image: phpmyadmin:5.2.2
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
    networks:
      - wpnet
    depends_on:
      - db
  
networks:
  wpnet:
    driver: bridge